---
- name: include_tasks play
  hosts: localhost
  connection: localhost
  gather_facts: False

  tasks:
    
    - name: include task
      include_tasks: "{{ filename }}"
      loop:
        - 1.1.1.1
        - 2.2.2.2
        - 3.3.3.3
        - 4.4.4.4
