---
- name: block and rescue play
  connection: localhost
  hosts: arista
  gather_facts: False

  tasks:
    - name: all tasks
      block:
        - name: configure dns servers
          vars:
            ansible_ssh_pass: "invalid"
          eos_config:
            lines:
              - ip name-server 1.1.1.1
              - ip name-server 2.2.2.2
      rescue:
        - name: try again
          vars:
            ansible_ssh_pass: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
          eos_config:
            lines:
              - ip name-server 1.1.1.1
              - ip name-server 2.2.2.2
      
