---
- name: include_tasks play
  hosts: localhost
  connection: localhost
  gather_facts: False
  vars_files:
    - host_vars/localhost.yml


  tasks:
    
    - name: include task
      import_tasks: "{{ filename }}" 
