---
- name: set system settings
  hosts: cisco1
  connection: local
  gather_facts: False
  
  tasks:
   - name: set stuff
     ios_system:
      name_servers: "{{ dns_servers }}"
      state: present

   - name: set other stuff
     ios_system:   
       domain_name: "{{ domain_name }}"
       hostname: "{{ hostname }}"
       state: present

