- name: clear logging play
  hosts: cisco6
  gather_facts: False
  tasks:
  - name: clear logging
    ios_command:
      commands: 
        - command: clear logging
          prompt: confirm
          answer: y
    register: output
  - name: print output
    debug:
      var: output
      

