---
- name: vlan config
  hosts: nxos1
  connection: localhost
  gather_facts: off
  tasks:
  - name: show vlans
    nxos_command:
      commands: show vlan id {{ item }}
    loop:
    - 1
    - 2
    - 3
    - 4
    register: vlans
  - name: debug print
    debug:
      var: vlans['results'][3]['stdout_lines']
