---
- name: env lookup
  hosts: arista
  connection: local
  gather_facts: False

  vars:
    ansible_user: pyclass
    ansible_ssh_pass: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"

  tasks:
    - name: show vlan
      eos_command:
        commands: show vlan
      register: output

    - name: print
      debug:
        var: output
