---

- name: Exercise6e - here there be errors.
  hosts: nxos 
  gather_facts: False

  tasks:
    - name: Executing command
      nxos_command:
        commands: show lldp neighbors
      register: output

    - debug:
        msg: "{{ output }}"
