---
- name: arista show ver regex search
  hosts: arista
  connection: localhost
  gather_facts: False
  
  tasks:

    - name: show ver output
      eos_command:
        commands: show version
      register: output

    - name: filter with regex
      set_fact:
        show_version: "{{ output['stdout'][0] | regex_findall('Software image version: (\\S+)') }}"

    - name: debug
      debug:
        var: show_version
